### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "testSumm3",
    "email": "testsumm3@example.com",
    "password": "password823"
}

### Login with the user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "testsumm3@example.com",
    "password": "password823"
}